# CodeDeploy Agent 가 참조하면서 배포를 진행하는 명세서

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/springboot-crud-codedeploy/ # s3에서 받아온 프로젝트의 위치 지정
    overwrite: yes

# CodeDeploy 에서 ec2 로 넘겨준 파일은 모두 ec2-user 권한 설정
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

# CodeDeploy 배포에는 각 단계별 수명주기가 존재. 수명주기에 따라 원하는 스크립트 실행
hooks:
  ApplicationStart:
    - location: sh/deploy.sh
      timeout: 60
      runas: ec2-user # ec2 에서 실행하는 사용자