spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  ROOT: DEBUG
  com.javahyang.springbootcrudcodedeploy: DEBUG
  pattern: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/deploy.log
