name: Sandbox Deploy

on:
#   push:
#     branches: [ dev ]
#   pull_request:
#     branches: [ dev ]

# 수동 실행
  workflow_dispatch:

jobs:
  build:
  # 어떤 OS 환경에서 실행할지 지정하는 runs-on
    runs-on: ubuntu-latest

    steps:
    # 현재 repository, branch 를 사용하도록 checkout
      - name: Checkout
        uses: actions/checkout@v2
        
    # springboot 프로젝트의 java 버전에 맞게 가상환경에 jdk 설치
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
    # gradlew 실행권한 설정
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash
        
    # build 전, 인수테스트(ATDD) 진행
      - name: ATDD with Gradle
        run: ./gradlew build test
        shell: bash

    # gradlew로 프로젝트 build
      - name: Build with Gradle
        run: ./gradlew build
        shell: bash
