name: Sandbox Deploy

on:
#   push:
#     branches: [ dev ]
#   pull_request:
#     branches: [ dev ]

# 수동 실행
  workflow_dispatch:

# github-actions 스크립트에서 사용할 변수 설정
env:
  # CodeDeploy 배포 그룹 이름
  ACTIVE: sandbox
  PROJECT_NAME: springboot-crud-codedeploy
  S3_BUCKET_NAME: ${{ secrets.SANDBOX_S3_BUCKET_NAME }}
  # S3 버킷 생성한 AWS 리전
  AWS_REGION: ap-northeast-2
  AWS_ACCESS_KEY_ID: ${{ secrets.SANDBOX_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SANDBOX_AWS_SECRET_ACCESS_KEY }}
  
jobs:
  build:
  # 어떤 OS 환경에서 실행할지 지정하는 runs-on
    runs-on: ubuntu-latest

    steps:
    # 현재 repository, branch 를 사용하도록 checkout
      - name: Checkout
        uses: actions/checkout@v2
        
    # springboot 프로젝트의 java 버전에 맞게 가상환경에 jdk 설치
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
    # gradlew 실행권한 설정
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash
        
    # build 전, 인수테스트(ATDD) 진행
      - name: ATDD with Gradle
        run: ./gradlew build test
        shell: bash

    # gradlew로 프로젝트 build
      - name: Build with Gradle
        run: ./gradlew build
        shell: bash
        
    # 필요한 파일들만 before-deploy 폴더로 이동
    # 프로그램을 실행하는 jar 파일
    # CodeDeploy Agent 실행에 필수적인 appspec.yml 파일
      - name: Before jar deploy
        run: mkdir -p before-deploy/build && cp build/libs/*.jar before-deploy/build/ && cp appspec.yml before-deploy/
        shell: bash

    # 배포스크립트 파일
      - name: Before sh deploy
        run: mkdir -p before-deploy/sh && cp sh/*.sh before-deploy/sh/
        shell: bash
        
    # before-deploy 폴더를 zip 파일로 압축
    # $GITHUB_SHA : 깃헙액션에서 제공하는 환경변수로 현재 workflow를 실행시키는 커밋의 해쉬값
      - name: Make zip file
        run: zip -r $GITHUB_SHA.zip ./before-deploy/*
        shell: bash

    # S3, CodeDeploy 권한있는 aws 사용자 계정 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

    # aws cli 명령어로 s3에 zip 파일로 압축한 jar 파일 업로드
      - name: Upload to S3
        run: aws s3 cp --region ${{ env.AWS_REGION }} ./$GITHUB_SHA.zip s3://${{ env.S3_BUCKET_NAME }}/${{ env.PROJECT_NAME }}/$GITHUB_SHA.zip
        shell: bash
        
    # CodeDeploy 배포 실행
      - name: Code Deploy
        run: aws deploy create-deployment --application-name ${{ env.PROJECT_NAME }} --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name ${{ env.ACTIVE }} --s3-location bucket=${{ env.S3_BUCKET_NAME }},bundleType=zip,key=${{ env.PROJECT_NAME }}/$GITHUB_SHA.zip
        shell: bash
